pm disable-user jp.softbank.mb.fivegservice
pm disable-user com.fujitsu.mobile_phone.ArrowsSetting
pm disable-user com.fujitsu.mobile_phone.passwordmanager
pm disable-user com.fcnt.mobile_phone.lamembers
pm disable-user com.fujitsu.mobile_phone.phoneappex
pm disable-user jp.softbank.mb.dmb
pm disable-user com.fujitsu.mobile_phone.TransferSupport
pm disable-user com.google.android.gms.supervision
pm disable-user com.fcnt.mobile_phone.fastmemo
pm disable-user com.fcnt.mobile_phone.arrowswallet
pm disable-user com.fujitsu.mobile_phone.Recommend
pm disable-user com.google.android.apps.nbu.files
pm disable-user com.fcnt.mobile_phone.gamelauncher
pm disable-user com.fcnt.mobile_phone.gamemode
pm disable-user com.fcnt.mobile_phone.gamegallery
pm disable-user com.google.android.googlequicksearchbox
pm disable-user com.google.android.videos
pm disable-user com.fujitsu.mobile_phone.Araikata
pm disable-user com.fujitsu.mobile_phone.healthcare
pm disable-user com.google.android.apps.tachyon
pm disable-user jp.co.softbank.OfficialApp
pm disable-user com.felicanetworks.mfm.main
pm disable-user com.felicanetworks.mfw.a.boot
pm disable-user com.felicanetworks.mfs
pm disable-user com.adobe.psmobile
pm disable-user jp.softbank.mb.cbrl
pm disable-user jp.co.softbank.wispr.froyo
pm disable-user jp.co.yahoo.android.yjtop
pm disable-user jp.co.yahoo.android.yshopping
pm disable-user com.google.android.apps.youtube.music
pm disable-user jp.softbank.mb.parentalcontrols
pm disable-user jp.softbank.mb.datamigration
pm disable-user com.fcnt.mobile_phone.rakurakucommunity
pm disable-user com.fcnt.mobile_phone.fcntappdownloader
pm disable-user jp.softbank.beginnerguide
pm disable-user jp.softbank.mb.bizlock
pm disable-user com.google.ar.core
pm disable-user com.fujitsu.mobile_phone.fjjuniormodeprovider
pm disable-user com.fujitsu.mobile_phone.fjjuniormode
pm disable-user com.fcnt.mobile_phone.privacymodesettings
pm disable-user com.fcnt.mobile_phone.privacymodeservice
pm disable-user com.fujitsu.mobile_phone.textcopyatanyscreen
pm disable-user jp.radiko.radio.player
pm disable-user com.fujitsu.mobile_phone.fjpedometerservice
pm disable-user com.fcnt.mobile_phone.fcntsarservice
pm disable-user com.fcnt.mobile_phone.sitechecker
pm disable-user com.fujitsu.mobile_phone.simplemode
pm disable-user com.fujitsu.mobile_phone.clearfontsettings
pm disable-user com.fujitsu.mobile_phone.screenmemo
pm disable-user com.fujitsu.mobile_phone.legiblefont
pm disable-user com.fujitsu.mobile_phone.voicememo
pm disable-user com.fujitsu.mobile_phone.slideinlauncher
pm disable-user com.fcnt.mobile_phone.meetingmode

