adb shell pm disable-user jp.softbank.mb.fivegservice
adb shell pm disable-user com.fujitsu.mobile_phone.ArrowsSetting
adb shell pm disable-user com.fujitsu.mobile_phone.passwordmanager
adb shell pm disable-user com.fcnt.mobile_phone.lamembers
adb shell pm disable-user com.fujitsu.mobile_phone.phoneappex
adb shell pm disable-user jp.softbank.mb.dmb
adb shell pm disable-user com.fujitsu.mobile_phone.TransferSupport
adb shell pm disable-user com.google.android.gms.supervision
adb shell pm disable-user com.fcnt.mobile_phone.fastmemo
adb shell pm disable-user com.fcnt.mobile_phone.arrowswallet
adb shell pm disable-user com.fujitsu.mobile_phone.Recommend
adb shell pm disable-user com.google.android.apps.nbu.files
adb shell pm disable-user com.fcnt.mobile_phone.gamelauncher
adb shell pm disable-user com.fcnt.mobile_phone.gamemode
adb shell pm disable-user com.fcnt.mobile_phone.gamegallery
adb shell pm disable-user com.google.android.googlequicksearchbox
adb shell pm disable-user com.google.android.videos
adb shell pm disable-user com.fujitsu.mobile_phone.Araikata
adb shell pm disable-user com.fujitsu.mobile_phone.healthcare
adb shell pm disable-user com.google.android.apps.tachyon
adb shell pm disable-user jp.co.softbank.OfficialApp
adb shell pm disable-user com.felicanetworks.mfm.main
adb shell pm disable-user com.felicanetworks.mfw.a.boot
adb shell pm disable-user com.felicanetworks.mfs
adb shell pm disable-user com.adobe.psmobile
adb shell pm disable-user jp.softbank.mb.cbrl
adb shell pm disable-user jp.co.softbank.wispr.froyo
adb shell pm disable-user jp.co.yahoo.android.yjtop
adb shell pm disable-user jp.co.yahoo.android.yshopping
adb shell pm disable-user com.google.android.apps.youtube.music
adb shell pm disable-user jp.softbank.mb.parentalcontrols
adb shell pm disable-user jp.softbank.mb.datamigration
adb shell pm disable-user com.fcnt.mobile_phone.rakurakucommunity
adb shell pm disable-user com.fcnt.mobile_phone.fcntappdownloader
adb shell pm disable-user jp.softbank.beginnerguide
adb shell pm disable-user jp.softbank.mb.bizlock
adb shell pm disable-user com.google.ar.core
adb shell pm disable-user com.fujitsu.mobile_phone.fjjuniormodeprovider
adb shell pm disable-user com.fujitsu.mobile_phone.fjjuniormode
adb shell pm disable-user com.fcnt.mobile_phone.privacymodesettings
adb shell pm disable-user com.fcnt.mobile_phone.privacymodeservice
adb shell pm disable-user com.fujitsu.mobile_phone.textcopyatanyscreen
adb shell pm disable-user jp.radiko.radio.player
adb shell pm disable-user com.fujitsu.mobile_phone.fjpedometerservice
adb shell pm disable-user com.fcnt.mobile_phone.fcntsarservice
adb shell pm disable-user com.fcnt.mobile_phone.sitechecker